#!/bin/sh
# This script runs after the package files are unpacked on the target system
case "$1" in
post)
    echo "Setting the owner for llamacpp directories..."
    chown -R llamacpp:llamacpp /var/lib/llamacpp
    chown -R llamacpp:llamacpp /etc/llamacpp
    chmod 750 /var/lib/llamacpp
    chmod 750 /etc/llamacpp

    echo "Setting the owner for Hugging Face directories..."
    chown root:llm /var/lib/llms
    chown root:llm /var/lib/llms/huggingface

    echo "Setting strict permissions for Hugging Face directory..."
    chmod 2770 /var/lib/llms
    chmod 2770 /var/lib/llms/huggingface
    # Apply the working Default ACL directly to LLM's home
    if command -v setfacl >/dev/null 2>&1; then
        echo "Applying production Default ACLs for dynamic model sharing..."
        setfacl -d -m g:llm:rwX /var/lib/llms
        setfacl -d -m g:llm:rwX /var/lib/llms/huggingface
        setfacl -d -m g:llm:rwX /var/lib/llms/flm
    fi
    # I apply for update, it's necessary to exist directory
    if [ -d "/var/lib/llms/huggingface/hub" ]; then
        echo "Apply to /var/lib/llms/huggingface/hub Default ACLs"
        setfacl -R -m g:llm:rwX  /var/lib/llms/huggingface/hub
        setfacl -d -m g:llm:rwX  /var/lib/llms/huggingface/hub
    fi
    ;;
esac
