#!/bin/sh
# This script runs after the package files are unpacked on the target system
case "$1" in
post)
    echo "Compiling GSettings schemas for Caffeine..."
    if [ -d /usr/share/gnome-shell/extensions/caffeine@patapon.info/schemas ]; then
        glib-compile-schemas /usr/share/gnome-shell/extensions/caffeine@patapon.info/schemas
    fi
    ;;
esac
