#!/bin/sh
# Runit service for Lemonade in BRGV-OS

# Redirect standard errors to the system log
exec 2>&1

# Ensure environment profiles are loaded if present
[ -r ./conf ] && . ./conf

# NATIVE BRGV-OS PERMISSION ASSURANCE (Runs as root before chpst)
chown -R lemonade:lemonade /var/lib/lemonade /etc/lemonade
chmod 750 /var/lib/lemonade /etc/lemonade

# Create directory lemonade in  /run (tmpfs) and give rights to user lemonade
mkdir -p /run/lemonade
chown lemonade:lemonade /run/lemonade
chmod 700 /run/lemonade

# If config.json not exist copy and set the owner and rights, usefully for first time start 
if [ ! -f /var/lib/lemonade/config.json ]; then
    cp /usr/share/lemonade-server/resources/defaults.json /var/lib/lemonade/config.json
    chown lemonade:lemonade /var/lib/lemonade/config.json
    chmod 640 /var/lib/lemonade/config.json
fi

# Export variables                                                               
export XDG_RUNTIME_DIR="/run/lemonade"
export RUNTIME_DIRECTORY="/run/lemonade"

# Verify the existence of the working directory before execution
cd /var/lib/lemonade || exit 1

export LEMONADE_CACHE_DIR="/var/lib/lemonade"
export LEMONADE_DATA_DIR="/var/lib/lemonade"
export LEMONADE_RESOURCES_DIR="/usr/share/lemonade-server/resources"
export HOME="/var/lib/lemonade"

# Launch the isolated server under the user and group designated for your data
exec chpst -U lemonade:lemonade lemond
