#!/bin/sh
# This script runs after the package files are unpacked on the target system
case "$1" in
post)
    echo "Compiling GSettings schemas for Blur My Shell..."
    if [ -d /usr/share/gnome-shell/extensions/blur-my-shell@aunetx/schemas ]; then
        glib-compile-schemas /usr/share/gnome-shell/extensions/blur-my-shell@aunetx/schemas
    fi
    ;;
esac
