#!/bin/sh
# This script runs after the package files are unpacked on the target system
case "$1" in
post)
    echo "Compiling GSettings schemas for light-dark-cursor-theme..."
    if [ -d /usr/share/gnome-shell/extensions/light-dark-cursor-theme@brgvos/schemas ]; then
        glib-compile-schemas /usr/share/gnome-shell/extensions/light-dark-cursor-theme@brgvos/schemas
    fi
    ;;
esac