#!/bin/sh
# This script runs after the package files are unpacked on the target system
case "$1" in
post)
    echo "Compiling GSettings schemas for Radio Kayra..."
    if [ -d /usr/share/gnome-shell/extensions/radiokayra@dokaton.com/schemas ]; then
        glib-compile-schemas /usr/share/gnome-shell/extensions/radiokayra@dokaton.com/schemas
    fi
    ;;
esac
