# Permit users from video/render group to block memory for NPU
@render   soft   memlock   unlimited
@render   hard   memlock   unlimited
@video    soft   memlock   unlimited
@video    hard   memlock   unlimited
