#!/bin/sh
# $1 = action (PRE/POST), $2 = pkgname, $3 = version

case "$1" in
post)
    MAIN_CONF="/etc/dracut.conf"
    # Set hostonly to no in the file /etc/dracut.conf   
    if [ -f "$MAIN_CONF" ]; then
        echo "[slimbook-kms-fix] Securing /etc/dracut.conf against kernel/DKMS updates..."
        # Delete any line with hostonly
        sed -i '/hostonly=/d' "$MAIN_CONF"
        # Added at the end of file the line with hostonly="no"
        echo 'hostonly="no"' >> "$MAIN_CONF"
        echo "File /etc/dracut.conf has been updated with hostonly=\"no\"."
    fi

    echo "Regenerating initramfs with Early KMS support for all kernels..."

    # Loop through all kernels found in /boot
    for kernel in /boot/vmlinuz-*; do
        # Skip if no kernels are found
        [ -e "$kernel" ] || continue

        # Extract the version from the filename (e.g., vmlinuz-6.1.20_1 -> 6.1.20_1)
        _ver="${kernel#*-}"
        
        echo "=> Processing kernel: ${_ver}"
        
        # Run dracut for each specific kernel version
        # It will use the /etc/dracut.conf.d/10-amdgpu.conf we just installed
        /usr/bin/dracut --force --kver "${_ver}"
    done

    echo "Initramfs regeneration complete."
    ;;
esac

