#!/bin/sh
# This script runs after the package files are unpacked on the target system
case "$1" in
post)
    echo "Setting the owner for ollama directories..."
    chown -R ollama:ollama /var/lib/ollama
    chown -R ollama:ollama /etc/ollama
    chmod 750 /var/lib/ollama /etc/ollama /etc/ollama/conf.d

    echo "Preparing dedicated subfolder for Ollama in the central repository..."
    mkdir -p /var/lib/llms/ollama
    chown root:llm /var/lib/llms /var/lib/llms/ollama
    chmod 2770 /var/lib/llms /var/lib/llms/ollama
    # Apply the working Default ACL directly to LLM's home
    if command -v setfacl >/dev/null 2>&1; then
        echo "Applying production Default ACLs for dynamic model sharing..."
        setfacl -d -m g:llm:rwX /var/lib/llms
        setfacl -d -m g:llm:rwX /var/lib/llms/ollama
    fi
    # I apply for update only, it's necessary to exist directory
    if [ -d "/var/lib/llms/ollama" ]; then
        echo "Apply to /var/lib/llms/ollama Default ACLs"
        setfacl -R -m g:llm:rwX  /var/lib/llms/ollama
        setfacl -d -m g:llm:rwX  /var/lib/llms/ollama
    fi
    echo ""
    ;;
esac
