#!/bin/sh
# This script runs after the package files are unpacked on the target system
case "$1" in
post)
    echo "Compiling GSettings schemas for Tiling Assistant..."
    if [ -d /usr/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/schemas ]; then
        glib-compile-schemas /usr/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/schemas
    fi
    ;;
esac
