# Core network configuration parameters for ollama
# Default value binds to localhost on port 11434
export OLLAMA_HOST="127.0.0.1:11434"

# Uncomment to allow network connections from all interfaces
# export OLLAMA_HOST="0.0.0.0:11434"

# Advanced runtime accelerators and library paths
#export OLLAMA_IGPU_ENABLE=1
#export HSA_OVERRIDE_GFX_VERSION=11.5.0

# CUDA Compute backend isolation (uncomment to restrict or force specific NVIDIA GPUs)
# export CUDA_VISIBLE_DEVICES="0"

# API KEY for authorise connection
# export OLLAMA_API_KEY=your_api_key
