#!/bin/sh
# This script runs after the package files are unpacked on the target system
case "$1" in
post)
    echo "Compiling GSettings schemas for accent-icons-theme..."
    if [ -d /usr/share/gnome-shell/extensions/accent-icons-theme@brgvos/schemas ]; then
        glib-compile-schemas /usr/share/gnome-shell/extensions/accent-icons-theme@brgvos/schemas
    fi
    ;;
esac
