PACKAGE_NAME="slimbook-keyboard"
PACKAGE_VERSION="0.2.8"
BUILT_MODULE_NAME[0]="clevo_platform"
DEST_MODULE_LOCATION[0]="/kernel/drivers/keyboard/clevo_platform"
AUTOINSTALL="yes"
MAKE="make -C ${kernel_source_dir} M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build modules"
